### ISSUE TITLE
Integrate Data INto System

### ISSUE THREAD

**Issue by winterstein** [OlleMuronde/LinkedInTest#3]

**Comment by winterstein** [comment]
Core: Profile -> cleaned-up profile + job category. Done :)

To Do: Time series, of profile -> job category at year uni +1, +2, +3...

**Comment by winterstein** [comment]
WEKA -- very soon. Issues with the GUI though, so using code driven?

Time series -- still to do.

**Comment by OlleMuronde** [comment]
Time series working somewhat. Requires some optimisations but good enough to submit
